[package]
name = "hydra-sdk-rust"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
reqwest = { version = "0.11", features = ["json"] }
hex = "0.4.3"
tokio-tungstenite = "0.27.0"
tungstenite = "0.27.0"
futures-util = "0.3.31"
anyhow = "1.0.101"
pallas = { version = "0.34.0", features = ["wallet"] }
uuid = { version = "1.20", features = ["v4"] }
